/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CalendarInfoResponse,
} from '../models/index';
import {
    CalendarInfoResponseFromJSON,
    CalendarInfoResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class CalendarApi extends runtime.BaseAPI {

    /**
     * Gets information about the user\'s calendars and calendar accounts.
     */
    async apiCalendarInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CalendarInfoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = await this.configuration.apiKey("x-csrf-token"); // csrfTokenHeader authentication
        }

        const response = await this.request({
            path: `/api/Calendar/Info`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CalendarInfoResponseFromJSON(jsonValue));
    }

    /**
     * Gets information about the user\'s calendars and calendar accounts.
     */
    async apiCalendarInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CalendarInfoResponse> {
        const response = await this.apiCalendarInfoGetRaw(initOverrides);
        return await response.value();
    }

}
