/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InboxItemsResponse,
} from '../models/index';
import {
    InboxItemsResponseFromJSON,
    InboxItemsResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class InboxApi extends runtime.BaseAPI {

    /**
     * Gets inbox items
     */
    async apiInboxItemsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InboxItemsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = await this.configuration.apiKey("x-csrf-token"); // csrfTokenHeader authentication
        }

        const response = await this.request({
            path: `/api/Inbox/Items`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InboxItemsResponseFromJSON(jsonValue));
    }

    /**
     * Gets inbox items
     */
    async apiInboxItemsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InboxItemsResponse> {
        const response = await this.apiInboxItemsGetRaw(initOverrides);
        return await response.value();
    }

}
