/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TagListResponse,
} from '../models/index';
import {
    TagListResponseFromJSON,
    TagListResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TagApi extends runtime.BaseAPI {

    /**
     * Gets the list of tags
     */
    async apiTagListGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TagListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-csrf-token"] = await this.configuration.apiKey("x-csrf-token"); // csrfTokenHeader authentication
        }

        const response = await this.request({
            path: `/api/tag/list`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TagListResponseFromJSON(jsonValue));
    }

    /**
     * Gets the list of tags
     */
    async apiTagListGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TagListResponse> {
        const response = await this.apiTagListGetRaw(initOverrides);
        return await response.value();
    }

}
