/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiAccountLoginPost200Response
 */
export interface ApiAccountLoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ApiAccountLoginPost200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the ApiAccountLoginPost200Response interface.
 */
export function instanceOfApiAccountLoginPost200Response(value: object): value is ApiAccountLoginPost200Response {
    return true;
}

export function ApiAccountLoginPost200ResponseFromJSON(json: any): ApiAccountLoginPost200Response {
    return ApiAccountLoginPost200ResponseFromJSONTyped(json, false);
}

export function ApiAccountLoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAccountLoginPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function ApiAccountLoginPost200ResponseToJSON(json: any): ApiAccountLoginPost200Response {
    return ApiAccountLoginPost200ResponseToJSONTyped(json, false);
}

export function ApiAccountLoginPost200ResponseToJSONTyped(value?: ApiAccountLoginPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

