/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Calendar
 */
export interface Calendar {
    /**
     * 
     * @type {number}
     * @memberof Calendar
     */
    calendarAccountId?: number;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    color?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Calendar
     */
    hidden?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    sourceUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Calendar
     */
    refreshRate?: number;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    syncId?: string;
    /**
     * 
     * @type {number}
     * @memberof Calendar
     */
    accessLevel?: number;
    /**
     * 
     * @type {string}
     * @memberof Calendar
     */
    syncStatus?: string;
    /**
     * 
     * @type {number}
     * @memberof Calendar
     */
    id?: number;
}

/**
 * Check if a given object implements the Calendar interface.
 */
export function instanceOfCalendar(value: object): value is Calendar {
    return true;
}

export function CalendarFromJSON(json: any): Calendar {
    return CalendarFromJSONTyped(json, false);
}

export function CalendarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Calendar {
    if (json == null) {
        return json;
    }
    return {
        
        'calendarAccountId': json['calendarAccountId'] == null ? undefined : json['calendarAccountId'],
        'title': json['Title'] == null ? undefined : json['Title'],
        'color': json['Color'] == null ? undefined : json['Color'],
        'hidden': json['Hidden'] == null ? undefined : json['Hidden'],
        'source': json['Source'] == null ? undefined : json['Source'],
        'sourceUrl': json['sourceUrl'] == null ? undefined : json['sourceUrl'],
        'refreshRate': json['refreshRate'] == null ? undefined : json['refreshRate'],
        'syncId': json['syncId'] == null ? undefined : json['syncId'],
        'accessLevel': json['AccessLevel'] == null ? undefined : json['AccessLevel'],
        'syncStatus': json['SyncStatus'] == null ? undefined : json['SyncStatus'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CalendarToJSON(json: any): Calendar {
    return CalendarToJSONTyped(json, false);
}

export function CalendarToJSONTyped(value?: Calendar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'calendarAccountId': value['calendarAccountId'],
        'Title': value['title'],
        'Color': value['color'],
        'Hidden': value['hidden'],
        'Source': value['source'],
        'sourceUrl': value['sourceUrl'],
        'refreshRate': value['refreshRate'],
        'syncId': value['syncId'],
        'AccessLevel': value['accessLevel'],
        'SyncStatus': value['syncStatus'],
        'id': value['id'],
    };
}

