/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CalendarAccount
 */
export interface CalendarAccount {
    /**
     * 
     * @type {string}
     * @memberof CalendarAccount
     */
    provider?: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarAccount
     */
    accountEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof CalendarAccount
     */
    syncState?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CalendarAccount
     */
    hasOptedInTo2WaySync?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CalendarAccount
     */
    id?: number;
}

/**
 * Check if a given object implements the CalendarAccount interface.
 */
export function instanceOfCalendarAccount(value: object): value is CalendarAccount {
    return true;
}

export function CalendarAccountFromJSON(json: any): CalendarAccount {
    return CalendarAccountFromJSONTyped(json, false);
}

export function CalendarAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'] == null ? undefined : json['provider'],
        'accountEmail': json['accountEmail'] == null ? undefined : json['accountEmail'],
        'syncState': json['syncState'] == null ? undefined : json['syncState'],
        'hasOptedInTo2WaySync': json['hasOptedInTo2WaySync'] == null ? undefined : json['hasOptedInTo2WaySync'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CalendarAccountToJSON(json: any): CalendarAccount {
    return CalendarAccountToJSONTyped(json, false);
}

export function CalendarAccountToJSONTyped(value?: CalendarAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'accountEmail': value['accountEmail'],
        'syncState': value['syncState'],
        'hasOptedInTo2WaySync': value['hasOptedInTo2WaySync'],
        'id': value['id'],
    };
}

