/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemShiftInfoMapValue } from './ItemShiftInfoMapValue';
import {
    ItemShiftInfoMapValueFromJSON,
    ItemShiftInfoMapValueFromJSONTyped,
    ItemShiftInfoMapValueToJSON,
    ItemShiftInfoMapValueToJSONTyped,
} from './ItemShiftInfoMapValue';
import type { ScheduleItemDiff } from './ScheduleItemDiff';
import {
    ScheduleItemDiffFromJSON,
    ScheduleItemDiffFromJSONTyped,
    ScheduleItemDiffToJSON,
    ScheduleItemDiffToJSONTyped,
} from './ScheduleItemDiff';
import type { DifferentVersions } from './DifferentVersions';
import {
    DifferentVersionsFromJSON,
    DifferentVersionsFromJSONTyped,
    DifferentVersionsToJSON,
    DifferentVersionsToJSONTyped,
} from './DifferentVersions';

/**
 * 
 * @export
 * @interface ChangePartialCompleteStatusResponse
 */
export interface ChangePartialCompleteStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ChangePartialCompleteStatusResponse
     */
    wholeTaskCompleted?: boolean;
    /**
     * 
     * @type {{ [key: string]: ItemShiftInfoMapValue; }}
     * @memberof ChangePartialCompleteStatusResponse
     */
    itemShiftInfoMap?: { [key: string]: ItemShiftInfoMapValue; };
    /**
     * 
     * @type {DifferentVersions}
     * @memberof ChangePartialCompleteStatusResponse
     */
    differentVersions?: DifferentVersions;
    /**
     * 
     * @type {ScheduleItemDiff}
     * @memberof ChangePartialCompleteStatusResponse
     */
    scheduleItemDiff?: ScheduleItemDiff;
}

/**
 * Check if a given object implements the ChangePartialCompleteStatusResponse interface.
 */
export function instanceOfChangePartialCompleteStatusResponse(value: object): value is ChangePartialCompleteStatusResponse {
    return true;
}

export function ChangePartialCompleteStatusResponseFromJSON(json: any): ChangePartialCompleteStatusResponse {
    return ChangePartialCompleteStatusResponseFromJSONTyped(json, false);
}

export function ChangePartialCompleteStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePartialCompleteStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'wholeTaskCompleted': json['wholeTaskCompleted'] == null ? undefined : json['wholeTaskCompleted'],
        'itemShiftInfoMap': json['itemShiftInfoMap'] == null ? undefined : (mapValues(json['itemShiftInfoMap'], ItemShiftInfoMapValueFromJSON)),
        'differentVersions': json['differentVersions'] == null ? undefined : DifferentVersionsFromJSON(json['differentVersions']),
        'scheduleItemDiff': json['scheduleItemDiff'] == null ? undefined : ScheduleItemDiffFromJSON(json['scheduleItemDiff']),
    };
}

export function ChangePartialCompleteStatusResponseToJSON(json: any): ChangePartialCompleteStatusResponse {
    return ChangePartialCompleteStatusResponseToJSONTyped(json, false);
}

export function ChangePartialCompleteStatusResponseToJSONTyped(value?: ChangePartialCompleteStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wholeTaskCompleted': value['wholeTaskCompleted'],
        'itemShiftInfoMap': value['itemShiftInfoMap'] == null ? undefined : (mapValues(value['itemShiftInfoMap'], ItemShiftInfoMapValueToJSON)),
        'differentVersions': DifferentVersionsToJSON(value['differentVersions']),
        'scheduleItemDiff': ScheduleItemDiffToJSON(value['scheduleItemDiff']),
    };
}

