/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureFlagOverrideInfo
 */
export interface FeatureFlagOverrideInfo {
    /**
     * 
     * @type {string}
     * @memberof FeatureFlagOverrideInfo
     */
    aesthetic?: string;
}

/**
 * Check if a given object implements the FeatureFlagOverrideInfo interface.
 */
export function instanceOfFeatureFlagOverrideInfo(value: object): value is FeatureFlagOverrideInfo {
    return true;
}

export function FeatureFlagOverrideInfoFromJSON(json: any): FeatureFlagOverrideInfo {
    return FeatureFlagOverrideInfoFromJSONTyped(json, false);
}

export function FeatureFlagOverrideInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureFlagOverrideInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'aesthetic': json['aesthetic'] == null ? undefined : json['aesthetic'],
    };
}

export function FeatureFlagOverrideInfoToJSON(json: any): FeatureFlagOverrideInfo {
    return FeatureFlagOverrideInfoToJSONTyped(json, false);
}

export function FeatureFlagOverrideInfoToJSONTyped(value?: FeatureFlagOverrideInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aesthetic': value['aesthetic'],
    };
}

