/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleResponseData } from './ScheduleResponseData';
import {
    ScheduleResponseDataFromJSON,
    ScheduleResponseDataFromJSONTyped,
    ScheduleResponseDataToJSON,
    ScheduleResponseDataToJSONTyped,
} from './ScheduleResponseData';

/**
 * 
 * @export
 * @interface GetScheduleResponse
 */
export interface GetScheduleResponse {
    /**
     * 
     * @type {ScheduleResponseData}
     * @memberof GetScheduleResponse
     */
    scheduleResponse?: ScheduleResponseData;
}

/**
 * Check if a given object implements the GetScheduleResponse interface.
 */
export function instanceOfGetScheduleResponse(value: object): value is GetScheduleResponse {
    return true;
}

export function GetScheduleResponseFromJSON(json: any): GetScheduleResponse {
    return GetScheduleResponseFromJSONTyped(json, false);
}

export function GetScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetScheduleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleResponse': json['scheduleResponse'] == null ? undefined : ScheduleResponseDataFromJSON(json['scheduleResponse']),
    };
}

export function GetScheduleResponseToJSON(json: any): GetScheduleResponse {
    return GetScheduleResponseToJSONTyped(json, false);
}

export function GetScheduleResponseToJSONTyped(value?: GetScheduleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scheduleResponse': ScheduleResponseDataToJSON(value['scheduleResponse']),
    };
}

