/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToDoListResponseData } from './ToDoListResponseData';
import {
    ToDoListResponseDataFromJSON,
    ToDoListResponseDataFromJSONTyped,
    ToDoListResponseDataToJSON,
    ToDoListResponseDataToJSONTyped,
} from './ToDoListResponseData';

/**
 * 
 * @export
 * @interface GetToDoListContentResponse
 */
export interface GetToDoListContentResponse {
    /**
     * 
     * @type {ToDoListResponseData}
     * @memberof GetToDoListContentResponse
     */
    toDoListResponse?: ToDoListResponseData;
}

/**
 * Check if a given object implements the GetToDoListContentResponse interface.
 */
export function instanceOfGetToDoListContentResponse(value: object): value is GetToDoListContentResponse {
    return true;
}

export function GetToDoListContentResponseFromJSON(json: any): GetToDoListContentResponse {
    return GetToDoListContentResponseFromJSONTyped(json, false);
}

export function GetToDoListContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetToDoListContentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'toDoListResponse': json['toDoListResponse'] == null ? undefined : ToDoListResponseDataFromJSON(json['toDoListResponse']),
    };
}

export function GetToDoListContentResponseToJSON(json: any): GetToDoListContentResponse {
    return GetToDoListContentResponseToJSONTyped(json, false);
}

export function GetToDoListContentResponseToJSONTyped(value?: GetToDoListContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'toDoListResponse': ToDoListResponseDataToJSON(value['toDoListResponse']),
    };
}

