/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncInfo } from './SyncInfo';
import {
    SyncInfoFromJSON,
    SyncInfoFromJSONTyped,
    SyncInfoToJSON,
    SyncInfoToJSONTyped,
} from './SyncInfo';
import type { DifferentVersions } from './DifferentVersions';
import {
    DifferentVersionsFromJSON,
    DifferentVersionsFromJSONTyped,
    DifferentVersionsToJSON,
    DifferentVersionsToJSONTyped,
} from './DifferentVersions';

/**
 * 
 * @export
 * @interface GetUpdatesResponse
 */
export interface GetUpdatesResponse {
    /**
     * 
     * @type {SyncInfo}
     * @memberof GetUpdatesResponse
     */
    syncInfo?: SyncInfo;
    /**
     * 
     * @type {DifferentVersions}
     * @memberof GetUpdatesResponse
     */
    differentVersions?: DifferentVersions;
}

/**
 * Check if a given object implements the GetUpdatesResponse interface.
 */
export function instanceOfGetUpdatesResponse(value: object): value is GetUpdatesResponse {
    return true;
}

export function GetUpdatesResponseFromJSON(json: any): GetUpdatesResponse {
    return GetUpdatesResponseFromJSONTyped(json, false);
}

export function GetUpdatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUpdatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'syncInfo': json['syncInfo'] == null ? undefined : SyncInfoFromJSON(json['syncInfo']),
        'differentVersions': json['differentVersions'] == null ? undefined : DifferentVersionsFromJSON(json['differentVersions']),
    };
}

export function GetUpdatesResponseToJSON(json: any): GetUpdatesResponse {
    return GetUpdatesResponseToJSONTyped(json, false);
}

export function GetUpdatesResponseToJSONTyped(value?: GetUpdatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'syncInfo': SyncInfoToJSON(value['syncInfo']),
        'differentVersions': DifferentVersionsToJSON(value['differentVersions']),
    };
}

