/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InboxItem
 */
export interface InboxItem {
    /**
     * 
     * @type {number}
     * @memberof InboxItem
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof InboxItem
     */
    title: string;
}

/**
 * Check if a given object implements the InboxItem interface.
 */
export function instanceOfInboxItem(value: object): value is InboxItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function InboxItemFromJSON(json: any): InboxItem {
    return InboxItemFromJSONTyped(json, false);
}

export function InboxItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['Title'],
    };
}

export function InboxItemToJSON(json: any): InboxItem {
    return InboxItemToJSONTyped(json, false);
}

export function InboxItemToJSONTyped(value?: InboxItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'Title': value['title'],
    };
}

