/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InboxItem } from './InboxItem';
import {
    InboxItemFromJSON,
    InboxItemFromJSONTyped,
    InboxItemToJSON,
    InboxItemToJSONTyped,
} from './InboxItem';

/**
 * 
 * @export
 * @interface InboxItemsResponse
 */
export interface InboxItemsResponse {
    /**
     * 
     * @type {Array<InboxItem>}
     * @memberof InboxItemsResponse
     */
    items?: Array<InboxItem>;
}

/**
 * Check if a given object implements the InboxItemsResponse interface.
 */
export function instanceOfInboxItemsResponse(value: object): value is InboxItemsResponse {
    return true;
}

export function InboxItemsResponseFromJSON(json: any): InboxItemsResponse {
    return InboxItemsResponseFromJSONTyped(json, false);
}

export function InboxItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InboxItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(InboxItemFromJSON)),
    };
}

export function InboxItemsResponseToJSON(json: any): InboxItemsResponse {
    return InboxItemsResponseToJSONTyped(json, false);
}

export function InboxItemsResponseToJSONTyped(value?: InboxItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(InboxItemToJSON)),
    };
}

