/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsAuthenticatedResponse
 */
export interface IsAuthenticatedResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IsAuthenticatedResponse
     */
    isAuthenticated?: boolean;
}

/**
 * Check if a given object implements the IsAuthenticatedResponse interface.
 */
export function instanceOfIsAuthenticatedResponse(value: object): value is IsAuthenticatedResponse {
    return true;
}

export function IsAuthenticatedResponseFromJSON(json: any): IsAuthenticatedResponse {
    return IsAuthenticatedResponseFromJSONTyped(json, false);
}

export function IsAuthenticatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsAuthenticatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isAuthenticated': json['isAuthenticated'] == null ? undefined : json['isAuthenticated'],
    };
}

export function IsAuthenticatedResponseToJSON(json: any): IsAuthenticatedResponse {
    return IsAuthenticatedResponseToJSONTyped(json, false);
}

export function IsAuthenticatedResponseToJSONTyped(value?: IsAuthenticatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isAuthenticated': value['isAuthenticated'],
    };
}

