/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemCore
 */
export interface ItemCore {
    /**
     * Item ID. 0 for new items.
     * @type {number}
     * @memberof ItemCore
     */
    id?: number;
    /**
     * Instance ID of the item, if applicable.
     * @type {number}
     * @memberof ItemCore
     */
    instanceID?: number;
    /**
     * Notes for the item.
     * @type {string}
     * @memberof ItemCore
     */
    notes?: string;
    /**
     * Due date and time for the item.
     * @type {Date}
     * @memberof ItemCore
     */
    dueDateTime?: Date | null;
    /**
     * Start date and time for the item.
     * @type {Date}
     * @memberof ItemCore
     */
    startDateTime?: Date;
    /**
     * End date and time for the item.
     * @type {Date}
     * @memberof ItemCore
     */
    endDateTime?: Date;
    /**
     * Do not start until this date and time.
     * @type {Date}
     * @memberof ItemCore
     */
    dontStartUntil?: Date;
    /**
     * Timezone for the item.
     * @type {string}
     * @memberof ItemCore
     */
    timeZone?: string;
    /**
     * Whether the item is auto-ignored.
     * @type {boolean}
     * @memberof ItemCore
     */
    isAutoIgnored?: boolean;
    /**
     * Title of the item.
     * @type {string}
     * @memberof ItemCore
     */
    title?: string;
    /**
     * Type of the item (e.g., task, event).
     * @type {string}
     * @memberof ItemCore
     */
    itemType?: string;
    /**
     * Progress in hours.
     * @type {number}
     * @memberof ItemCore
     */
    progressHours?: number;
    /**
     * Progress in minutes.
     * @type {number}
     * @memberof ItemCore
     */
    progressMinutes?: number;
    /**
     * Minimum length of the item in total minutes.
     * @type {number}
     * @memberof ItemCore
     */
    minLengthTotalMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    bufferTimeBeforeHours?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    bufferTimeBeforeMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    bufferTimeAfterHours?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    bufferTimeAfterMinutes?: number;
    /**
     * Whether the item marks time as busy.
     * @type {boolean}
     * @memberof ItemCore
     */
    busy?: boolean;
    /**
     * Whether the item has a fixed time.
     * @type {boolean}
     * @memberof ItemCore
     */
    fixedTime?: boolean;
    /**
     * Whether the item is an all-day event.
     * @type {boolean}
     * @memberof ItemCore
     */
    allDay?: boolean;
    /**
     * Repeat type (e.g., Never, Daily, Weekly).
     * @type {string}
     * @memberof ItemCore
     */
    repeatType?: string;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    interval?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    sunday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    monday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    tuesday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    wednesday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    thursday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    friday?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemCore
     */
    saturday?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ItemCore
     */
    monthlyType?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemCore
     */
    dates?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    monthOrdinal?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    weekDay?: number;
    /**
     * 
     * @type {string}
     * @memberof ItemCore
     */
    endRepeatType?: string;
    /**
     * 
     * @type {Date}
     * @memberof ItemCore
     */
    endRepeatDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ItemCore
     */
    numOccurrences?: number;
    /**
     * Priority of the item.
     * @type {number}
     * @memberof ItemCore
     */
    priority?: number;
    /**
     * Custom color for the item (hex code).
     * @type {string}
     * @memberof ItemCore
     */
    customColor?: string | null;
    /**
     * ID of the calendar this item belongs to.
     * @type {number}
     * @memberof ItemCore
     */
    calendarId?: number;
    /**
     * ID of the time profile associated with this item.
     * @type {number}
     * @memberof ItemCore
     */
    timeProfileId?: number | null;
    /**
     * Comma-separated string of tag IDs for create/update.
     * @type {string}
     * @memberof ItemCore
     */
    tagIds?: string;
    /**
     * 
     * @type {string}
     * @memberof ItemCore
     */
    location?: string | null;
}

/**
 * Check if a given object implements the ItemCore interface.
 */
export function instanceOfItemCore(value: object): value is ItemCore {
    return true;
}

export function ItemCoreFromJSON(json: any): ItemCore {
    return ItemCoreFromJSONTyped(json, false);
}

export function ItemCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemCore {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'instanceID': json['InstanceID'] == null ? undefined : json['InstanceID'],
        'notes': json['Notes'] == null ? undefined : json['Notes'],
        'dueDateTime': json['DueDateTime'] == null ? undefined : (new Date(json['DueDateTime'])),
        'startDateTime': json['StartDateTime'] == null ? undefined : (new Date(json['StartDateTime'])),
        'endDateTime': json['EndDateTime'] == null ? undefined : (new Date(json['EndDateTime'])),
        'dontStartUntil': json['DontStartUntil'] == null ? undefined : (new Date(json['DontStartUntil'])),
        'timeZone': json['TimeZone'] == null ? undefined : json['TimeZone'],
        'isAutoIgnored': json['IsAutoIgnored'] == null ? undefined : json['IsAutoIgnored'],
        'title': json['Title'] == null ? undefined : json['Title'],
        'itemType': json['ItemType'] == null ? undefined : json['ItemType'],
        'progressHours': json['ProgressHours'] == null ? undefined : json['ProgressHours'],
        'progressMinutes': json['ProgressMinutes'] == null ? undefined : json['ProgressMinutes'],
        'minLengthTotalMinutes': json['minLengthTotalMinutes'] == null ? undefined : json['minLengthTotalMinutes'],
        'bufferTimeBeforeHours': json['BufferTimeBeforeHours'] == null ? undefined : json['BufferTimeBeforeHours'],
        'bufferTimeBeforeMinutes': json['BufferTimeBeforeMinutes'] == null ? undefined : json['BufferTimeBeforeMinutes'],
        'bufferTimeAfterHours': json['BufferTimeAfterHours'] == null ? undefined : json['BufferTimeAfterHours'],
        'bufferTimeAfterMinutes': json['BufferTimeAfterMinutes'] == null ? undefined : json['BufferTimeAfterMinutes'],
        'busy': json['Busy'] == null ? undefined : json['Busy'],
        'fixedTime': json['FixedTime'] == null ? undefined : json['FixedTime'],
        'allDay': json['AllDay'] == null ? undefined : json['AllDay'],
        'repeatType': json['RepeatType'] == null ? undefined : json['RepeatType'],
        'interval': json['Interval'] == null ? undefined : json['Interval'],
        'sunday': json['Sunday'] == null ? undefined : json['Sunday'],
        'monday': json['Monday'] == null ? undefined : json['Monday'],
        'tuesday': json['Tuesday'] == null ? undefined : json['Tuesday'],
        'wednesday': json['Wednesday'] == null ? undefined : json['Wednesday'],
        'thursday': json['Thursday'] == null ? undefined : json['Thursday'],
        'friday': json['Friday'] == null ? undefined : json['Friday'],
        'saturday': json['Saturday'] == null ? undefined : json['Saturday'],
        'monthlyType': json['MonthlyType'] == null ? undefined : json['MonthlyType'],
        'dates': json['Dates'] == null ? undefined : json['Dates'],
        'monthOrdinal': json['MonthOrdinal'] == null ? undefined : json['MonthOrdinal'],
        'weekDay': json['WeekDay'] == null ? undefined : json['WeekDay'],
        'endRepeatType': json['EndRepeatType'] == null ? undefined : json['EndRepeatType'],
        'endRepeatDate': json['EndRepeatDate'] == null ? undefined : (new Date(json['EndRepeatDate'])),
        'numOccurrences': json['NumOccurrences'] == null ? undefined : json['NumOccurrences'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'customColor': json['customColor'] == null ? undefined : json['customColor'],
        'calendarId': json['calendarId'] == null ? undefined : json['calendarId'],
        'timeProfileId': json['timeProfileId'] == null ? undefined : json['timeProfileId'],
        'tagIds': json['tagIds'] == null ? undefined : json['tagIds'],
        'location': json['Location'] == null ? undefined : json['Location'],
    };
}

export function ItemCoreToJSON(json: any): ItemCore {
    return ItemCoreToJSONTyped(json, false);
}

export function ItemCoreToJSONTyped(value?: ItemCore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'InstanceID': value['instanceID'],
        'Notes': value['notes'],
        'DueDateTime': value['dueDateTime'] == null ? undefined : ((value['dueDateTime'] as any).toISOString()),
        'StartDateTime': value['startDateTime'] == null ? undefined : ((value['startDateTime']).toISOString()),
        'EndDateTime': value['endDateTime'] == null ? undefined : ((value['endDateTime']).toISOString()),
        'DontStartUntil': value['dontStartUntil'] == null ? undefined : ((value['dontStartUntil']).toISOString()),
        'TimeZone': value['timeZone'],
        'IsAutoIgnored': value['isAutoIgnored'],
        'Title': value['title'],
        'ItemType': value['itemType'],
        'ProgressHours': value['progressHours'],
        'ProgressMinutes': value['progressMinutes'],
        'minLengthTotalMinutes': value['minLengthTotalMinutes'],
        'BufferTimeBeforeHours': value['bufferTimeBeforeHours'],
        'BufferTimeBeforeMinutes': value['bufferTimeBeforeMinutes'],
        'BufferTimeAfterHours': value['bufferTimeAfterHours'],
        'BufferTimeAfterMinutes': value['bufferTimeAfterMinutes'],
        'Busy': value['busy'],
        'FixedTime': value['fixedTime'],
        'AllDay': value['allDay'],
        'RepeatType': value['repeatType'],
        'Interval': value['interval'],
        'Sunday': value['sunday'],
        'Monday': value['monday'],
        'Tuesday': value['tuesday'],
        'Wednesday': value['wednesday'],
        'Thursday': value['thursday'],
        'Friday': value['friday'],
        'Saturday': value['saturday'],
        'MonthlyType': value['monthlyType'],
        'Dates': value['dates'],
        'MonthOrdinal': value['monthOrdinal'],
        'WeekDay': value['weekDay'],
        'EndRepeatType': value['endRepeatType'],
        'EndRepeatDate': value['endRepeatDate'] == null ? undefined : ((value['endRepeatDate']).toISOString()),
        'NumOccurrences': value['numOccurrences'],
        'priority': value['priority'],
        'customColor': value['customColor'],
        'calendarId': value['calendarId'],
        'timeProfileId': value['timeProfileId'],
        'tagIds': value['tagIds'],
        'Location': value['location'],
    };
}

