/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemSettings
 */
export interface ItemSettings {
    /**
     * 
     * @type {boolean}
     * @memberof ItemSettings
     */
    moreOptionsExpanded?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ItemSettings
     */
    splittable?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ItemSettings
     */
    minLengthTotalMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSettings
     */
    bufferTimeBeforeHours?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSettings
     */
    bufferTimeBeforeMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSettings
     */
    bufferTimeAfterHours?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSettings
     */
    bufferTimeAfterMinutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemSettings
     */
    durationTotalMinutes?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ItemSettings
     */
    useSmartColorCoding?: boolean;
}

/**
 * Check if a given object implements the ItemSettings interface.
 */
export function instanceOfItemSettings(value: object): value is ItemSettings {
    return true;
}

export function ItemSettingsFromJSON(json: any): ItemSettings {
    return ItemSettingsFromJSONTyped(json, false);
}

export function ItemSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'moreOptionsExpanded': json['moreOptionsExpanded'] == null ? undefined : json['moreOptionsExpanded'],
        'splittable': json['splittable'] == null ? undefined : json['splittable'],
        'minLengthTotalMinutes': json['minLengthTotalMinutes'] == null ? undefined : json['minLengthTotalMinutes'],
        'bufferTimeBeforeHours': json['bufferTimeBeforeHours'] == null ? undefined : json['bufferTimeBeforeHours'],
        'bufferTimeBeforeMinutes': json['bufferTimeBeforeMinutes'] == null ? undefined : json['bufferTimeBeforeMinutes'],
        'bufferTimeAfterHours': json['bufferTimeAfterHours'] == null ? undefined : json['bufferTimeAfterHours'],
        'bufferTimeAfterMinutes': json['bufferTimeAfterMinutes'] == null ? undefined : json['bufferTimeAfterMinutes'],
        'durationTotalMinutes': json['durationTotalMinutes'] == null ? undefined : json['durationTotalMinutes'],
        'useSmartColorCoding': json['useSmartColorCoding'] == null ? undefined : json['useSmartColorCoding'],
    };
}

export function ItemSettingsToJSON(json: any): ItemSettings {
    return ItemSettingsToJSONTyped(json, false);
}

export function ItemSettingsToJSONTyped(value?: ItemSettings | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'moreOptionsExpanded': value['moreOptionsExpanded'],
        'splittable': value['splittable'],
        'minLengthTotalMinutes': value['minLengthTotalMinutes'],
        'bufferTimeBeforeHours': value['bufferTimeBeforeHours'],
        'bufferTimeBeforeMinutes': value['bufferTimeBeforeMinutes'],
        'bufferTimeAfterHours': value['bufferTimeAfterHours'],
        'bufferTimeAfterMinutes': value['bufferTimeAfterMinutes'],
        'durationTotalMinutes': value['durationTotalMinutes'],
        'useSmartColorCoding': value['useSmartColorCoding'],
    };
}

