/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleItemDiff } from './ScheduleItemDiff';
import {
    ScheduleItemDiffFromJSON,
    ScheduleItemDiffFromJSONTyped,
    ScheduleItemDiffToJSON,
    ScheduleItemDiffToJSONTyped,
} from './ScheduleItemDiff';
import type { DifferentVersions } from './DifferentVersions';
import {
    DifferentVersionsFromJSON,
    DifferentVersionsFromJSONTyped,
    DifferentVersionsToJSON,
    DifferentVersionsToJSONTyped,
} from './DifferentVersions';

/**
 * 
 * @export
 * @interface ItemEditResponse
 */
export interface ItemEditResponse {
    /**
     * 
     * @type {number}
     * @memberof ItemEditResponse
     */
    numRepeatingAutoScheduledTasks?: number | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ItemEditResponse
     */
    itemShiftInfoMap?: { [key: string]: any; };
    /**
     * 
     * @type {DifferentVersions}
     * @memberof ItemEditResponse
     */
    differentVersions?: DifferentVersions;
    /**
     * 
     * @type {ScheduleItemDiff}
     * @memberof ItemEditResponse
     */
    scheduleItemDiff?: ScheduleItemDiff;
}

/**
 * Check if a given object implements the ItemEditResponse interface.
 */
export function instanceOfItemEditResponse(value: object): value is ItemEditResponse {
    return true;
}

export function ItemEditResponseFromJSON(json: any): ItemEditResponse {
    return ItemEditResponseFromJSONTyped(json, false);
}

export function ItemEditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemEditResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'numRepeatingAutoScheduledTasks': json['numRepeatingAutoScheduledTasks'] == null ? undefined : json['numRepeatingAutoScheduledTasks'],
        'itemShiftInfoMap': json['itemShiftInfoMap'] == null ? undefined : json['itemShiftInfoMap'],
        'differentVersions': json['differentVersions'] == null ? undefined : DifferentVersionsFromJSON(json['differentVersions']),
        'scheduleItemDiff': json['scheduleItemDiff'] == null ? undefined : ScheduleItemDiffFromJSON(json['scheduleItemDiff']),
    };
}

export function ItemEditResponseToJSON(json: any): ItemEditResponse {
    return ItemEditResponseToJSONTyped(json, false);
}

export function ItemEditResponseToJSONTyped(value?: ItemEditResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numRepeatingAutoScheduledTasks': value['numRepeatingAutoScheduledTasks'],
        'itemShiftInfoMap': value['itemShiftInfoMap'],
        'differentVersions': DifferentVersionsToJSON(value['differentVersions']),
        'scheduleItemDiff': ScheduleItemDiffToJSON(value['scheduleItemDiff']),
    };
}

