/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DifferentVersions } from './DifferentVersions';
import {
    DifferentVersionsFromJSON,
    DifferentVersionsFromJSONTyped,
    DifferentVersionsToJSON,
    DifferentVersionsToJSONTyped,
} from './DifferentVersions';

/**
 * 
 * @export
 * @interface ItemCreateResponse
 */
export interface ItemCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof ItemCreateResponse
     */
    newItemId?: number;
    /**
     * 
     * @type {number}
     * @memberof ItemCreateResponse
     */
    numRepeatingAutoScheduledTasks?: number | null;
    /**
     * 
     * @type {DifferentVersions}
     * @memberof ItemCreateResponse
     */
    differentVersions?: DifferentVersions;
    /**
     * 
     * @type {number}
     * @memberof ItemCreateResponse
     */
    numAutoScheduledTasksAdded?: number | null;
}

/**
 * Check if a given object implements the ItemCreateResponse interface.
 */
export function instanceOfItemCreateResponse(value: object): value is ItemCreateResponse {
    return true;
}

export function ItemCreateResponseFromJSON(json: any): ItemCreateResponse {
    return ItemCreateResponseFromJSONTyped(json, false);
}

export function ItemCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'newItemId': json['newItemId'] == null ? undefined : json['newItemId'],
        'numRepeatingAutoScheduledTasks': json['numRepeatingAutoScheduledTasks'] == null ? undefined : json['numRepeatingAutoScheduledTasks'],
        'differentVersions': json['differentVersions'] == null ? undefined : DifferentVersionsFromJSON(json['differentVersions']),
        'numAutoScheduledTasksAdded': json['numAutoScheduledTasksAdded'] == null ? undefined : json['numAutoScheduledTasksAdded'],
    };
}

export function ItemCreateResponseToJSON(json: any): ItemCreateResponse {
    return ItemCreateResponseToJSONTyped(json, false);
}

export function ItemCreateResponseToJSONTyped(value?: ItemCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newItemId': value['newItemId'],
        'numRepeatingAutoScheduledTasks': value['numRepeatingAutoScheduledTasks'],
        'differentVersions': DifferentVersionsToJSON(value['differentVersions']),
        'numAutoScheduledTasksAdded': value['numAutoScheduledTasksAdded'],
    };
}

