/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemFull } from './ItemFull';
import {
    ItemFullFromJSON,
    ItemFullFromJSONTyped,
    ItemFullToJSON,
    ItemFullToJSONTyped,
} from './ItemFull';
import type { SchedulingStatusInfo } from './SchedulingStatusInfo';
import {
    SchedulingStatusInfoFromJSON,
    SchedulingStatusInfoFromJSONTyped,
    SchedulingStatusInfoToJSON,
    SchedulingStatusInfoToJSONTyped,
} from './SchedulingStatusInfo';
import type { ScheduleItemData } from './ScheduleItemData';
import {
    ScheduleItemDataFromJSON,
    ScheduleItemDataFromJSONTyped,
    ScheduleItemDataToJSON,
    ScheduleItemDataToJSONTyped,
} from './ScheduleItemData';

/**
 * 
 * @export
 * @interface ItemEditGetDataResponse
 */
export interface ItemEditGetDataResponse {
    /**
     * 
     * @type {ItemFull}
     * @memberof ItemEditGetDataResponse
     */
    item?: ItemFull;
    /**
     * 
     * @type {SchedulingStatusInfo}
     * @memberof ItemEditGetDataResponse
     */
    schedulingStatusInfo?: SchedulingStatusInfo;
    /**
     * 
     * @type {Array<ScheduleItemData>}
     * @memberof ItemEditGetDataResponse
     */
    scheduleItems?: Array<ScheduleItemData>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ItemEditGetDataResponse
     */
    repeatingAutoScheduledTaskIds?: Array<number> | null;
}

/**
 * Check if a given object implements the ItemEditGetDataResponse interface.
 */
export function instanceOfItemEditGetDataResponse(value: object): value is ItemEditGetDataResponse {
    return true;
}

export function ItemEditGetDataResponseFromJSON(json: any): ItemEditGetDataResponse {
    return ItemEditGetDataResponseFromJSONTyped(json, false);
}

export function ItemEditGetDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemEditGetDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'item': json['item'] == null ? undefined : ItemFullFromJSON(json['item']),
        'schedulingStatusInfo': json['schedulingStatusInfo'] == null ? undefined : SchedulingStatusInfoFromJSON(json['schedulingStatusInfo']),
        'scheduleItems': json['scheduleItems'] == null ? undefined : ((json['scheduleItems'] as Array<any>).map(ScheduleItemDataFromJSON)),
        'repeatingAutoScheduledTaskIds': json['repeatingAutoScheduledTaskIds'] == null ? undefined : json['repeatingAutoScheduledTaskIds'],
    };
}

export function ItemEditGetDataResponseToJSON(json: any): ItemEditGetDataResponse {
    return ItemEditGetDataResponseToJSONTyped(json, false);
}

export function ItemEditGetDataResponseToJSONTyped(value?: ItemEditGetDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item': ItemFullToJSON(value['item']),
        'schedulingStatusInfo': SchedulingStatusInfoToJSON(value['schedulingStatusInfo']),
        'scheduleItems': value['scheduleItems'] == null ? undefined : ((value['scheduleItems'] as Array<any>).map(ScheduleItemDataToJSON)),
        'repeatingAutoScheduledTaskIds': value['repeatingAutoScheduledTaskIds'],
    };
}

