/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemFull } from './ItemFull';
import {
    ItemFullFromJSON,
    ItemFullFromJSONTyped,
    ItemFullToJSON,
    ItemFullToJSONTyped,
} from './ItemFull';

/**
 * 
 * @export
 * @interface ItemShiftInfoMapValue
 */
export interface ItemShiftInfoMapValue {
    /**
     * 
     * @type {{ [key: string]: ItemFull; }}
     * @memberof ItemShiftInfoMapValue
     */
    oldInstanceIdsToNewItems?: { [key: string]: ItemFull; };
    /**
     * 
     * @type {object}
     * @memberof ItemShiftInfoMapValue
     */
    instanceIdShiftInfo?: object | null;
}

/**
 * Check if a given object implements the ItemShiftInfoMapValue interface.
 */
export function instanceOfItemShiftInfoMapValue(value: object): value is ItemShiftInfoMapValue {
    return true;
}

export function ItemShiftInfoMapValueFromJSON(json: any): ItemShiftInfoMapValue {
    return ItemShiftInfoMapValueFromJSONTyped(json, false);
}

export function ItemShiftInfoMapValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemShiftInfoMapValue {
    if (json == null) {
        return json;
    }
    return {
        
        'oldInstanceIdsToNewItems': json['oldInstanceIdsToNewItems'] == null ? undefined : (mapValues(json['oldInstanceIdsToNewItems'], ItemFullFromJSON)),
        'instanceIdShiftInfo': json['instanceIdShiftInfo'] == null ? undefined : json['instanceIdShiftInfo'],
    };
}

export function ItemShiftInfoMapValueToJSON(json: any): ItemShiftInfoMapValue {
    return ItemShiftInfoMapValueToJSONTyped(json, false);
}

export function ItemShiftInfoMapValueToJSONTyped(value?: ItemShiftInfoMapValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldInstanceIdsToNewItems': value['oldInstanceIdsToNewItems'] == null ? undefined : (mapValues(value['oldInstanceIdsToNewItems'], ItemFullToJSON)),
        'instanceIdShiftInfo': value['instanceIdShiftInfo'],
    };
}

