/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginSuccessResponse
 */
export interface LoginSuccessResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginSuccessResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the LoginSuccessResponse interface.
 */
export function instanceOfLoginSuccessResponse(value: object): value is LoginSuccessResponse {
    return true;
}

export function LoginSuccessResponseFromJSON(json: any): LoginSuccessResponse {
    return LoginSuccessResponseFromJSONTyped(json, false);
}

export function LoginSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function LoginSuccessResponseToJSON(json: any): LoginSuccessResponse {
    return LoginSuccessResponseToJSONTyped(json, false);
}

export function LoginSuccessResponseToJSONTyped(value?: LoginSuccessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

