/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemFull } from './ItemFull';
import {
    ItemFullFromJSON,
    ItemFullFromJSONTyped,
    ItemFullToJSON,
    ItemFullToJSONTyped,
} from './ItemFull';

/**
 * Represents a schedule item that has been modified, often returned in diffs.
 * @export
 * @interface ModifiedScheduleItem
 */
export interface ModifiedScheduleItem {
    /**
     * Often 0 if the primary ID is within the nested Item object.
     * @type {number}
     * @memberof ModifiedScheduleItem
     */
    itemID?: number;
    /**
     * 
     * @type {ItemFull}
     * @memberof ModifiedScheduleItem
     */
    item?: ItemFull;
    /**
     * 
     * @type {number}
     * @memberof ModifiedScheduleItem
     */
    instanceID?: number;
    /**
     * 
     * @type {Date}
     * @memberof ModifiedScheduleItem
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModifiedScheduleItem
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ModifiedScheduleItem
     */
    color?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModifiedScheduleItem
     */
    thisPartCompleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ModifiedScheduleItem
     */
    instanceStartDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ModifiedScheduleItem
     */
    instanceEndDateTime?: Date;
    /**
     * The ID of this specific schedule item instance/part.
     * @type {number}
     * @memberof ModifiedScheduleItem
     */
    id?: number;
}

/**
 * Check if a given object implements the ModifiedScheduleItem interface.
 */
export function instanceOfModifiedScheduleItem(value: object): value is ModifiedScheduleItem {
    return true;
}

export function ModifiedScheduleItemFromJSON(json: any): ModifiedScheduleItem {
    return ModifiedScheduleItemFromJSONTyped(json, false);
}

export function ModifiedScheduleItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifiedScheduleItem {
    if (json == null) {
        return json;
    }
    return {
        
        'itemID': json['ItemID'] == null ? undefined : json['ItemID'],
        'item': json['Item'] == null ? undefined : ItemFullFromJSON(json['Item']),
        'instanceID': json['InstanceID'] == null ? undefined : json['InstanceID'],
        'startTime': json['StartTime'] == null ? undefined : (new Date(json['StartTime'])),
        'endTime': json['EndTime'] == null ? undefined : (new Date(json['EndTime'])),
        'color': json['Color'] == null ? undefined : json['Color'],
        'thisPartCompleted': json['ThisPartCompleted'] == null ? undefined : json['ThisPartCompleted'],
        'instanceStartDateTime': json['InstanceStartDateTime'] == null ? undefined : (new Date(json['InstanceStartDateTime'])),
        'instanceEndDateTime': json['InstanceEndDateTime'] == null ? undefined : (new Date(json['InstanceEndDateTime'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ModifiedScheduleItemToJSON(json: any): ModifiedScheduleItem {
    return ModifiedScheduleItemToJSONTyped(json, false);
}

export function ModifiedScheduleItemToJSONTyped(value?: ModifiedScheduleItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ItemID': value['itemID'],
        'Item': ItemFullToJSON(value['item']),
        'InstanceID': value['instanceID'],
        'StartTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'EndTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'Color': value['color'],
        'ThisPartCompleted': value['thisPartCompleted'],
        'InstanceStartDateTime': value['instanceStartDateTime'] == null ? undefined : ((value['instanceStartDateTime']).toISOString()),
        'InstanceEndDateTime': value['instanceEndDateTime'] == null ? undefined : ((value['instanceEndDateTime']).toISOString()),
        'id': value['id'],
    };
}

