/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DifferentVersions } from './DifferentVersions';
import {
    DifferentVersionsFromJSON,
    DifferentVersionsFromJSONTyped,
    DifferentVersionsToJSON,
    DifferentVersionsToJSONTyped,
} from './DifferentVersions';

/**
 * 
 * @export
 * @interface MultipleDeleteResponse
 */
export interface MultipleDeleteResponse {
    /**
     * 
     * @type {DifferentVersions}
     * @memberof MultipleDeleteResponse
     */
    differentVersions?: DifferentVersions;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof MultipleDeleteResponse
     */
    itemShiftInfoMap?: { [key: string]: any; };
}

/**
 * Check if a given object implements the MultipleDeleteResponse interface.
 */
export function instanceOfMultipleDeleteResponse(value: object): value is MultipleDeleteResponse {
    return true;
}

export function MultipleDeleteResponseFromJSON(json: any): MultipleDeleteResponse {
    return MultipleDeleteResponseFromJSONTyped(json, false);
}

export function MultipleDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'differentVersions': json['differentVersions'] == null ? undefined : DifferentVersionsFromJSON(json['differentVersions']),
        'itemShiftInfoMap': json['itemShiftInfoMap'] == null ? undefined : json['itemShiftInfoMap'],
    };
}

export function MultipleDeleteResponseToJSON(json: any): MultipleDeleteResponse {
    return MultipleDeleteResponseToJSONTyped(json, false);
}

export function MultipleDeleteResponseToJSONTyped(value?: MultipleDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'differentVersions': DifferentVersionsToJSON(value['differentVersions']),
        'itemShiftInfoMap': value['itemShiftInfoMap'],
    };
}

