/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnboardingInfo
 */
export interface OnboardingInfo {
    /**
     * 
     * @type {string}
     * @memberof OnboardingInfo
     */
    onboardingStage?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OnboardingInfo
     */
    numAutoScheduledTasksAdded?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OnboardingInfo
     */
    completedSteps?: Array<string> | null;
}

/**
 * Check if a given object implements the OnboardingInfo interface.
 */
export function instanceOfOnboardingInfo(value: object): value is OnboardingInfo {
    return true;
}

export function OnboardingInfoFromJSON(json: any): OnboardingInfo {
    return OnboardingInfoFromJSONTyped(json, false);
}

export function OnboardingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnboardingInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'onboardingStage': json['onboardingStage'] == null ? undefined : json['onboardingStage'],
        'numAutoScheduledTasksAdded': json['numAutoScheduledTasksAdded'] == null ? undefined : json['numAutoScheduledTasksAdded'],
        'completedSteps': json['completedSteps'] == null ? undefined : json['completedSteps'],
    };
}

export function OnboardingInfoToJSON(json: any): OnboardingInfo {
    return OnboardingInfoToJSONTyped(json, false);
}

export function OnboardingInfoToJSONTyped(value?: OnboardingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'onboardingStage': value['onboardingStage'],
        'numAutoScheduledTasksAdded': value['numAutoScheduledTasksAdded'],
        'completedSteps': value['completedSteps'],
    };
}

