/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncInfo } from './SyncInfo';
import {
    SyncInfoFromJSON,
    SyncInfoFromJSONTyped,
    SyncInfoToJSON,
    SyncInfoToJSONTyped,
} from './SyncInfo';
import type { DifferentVersions } from './DifferentVersions';
import {
    DifferentVersionsFromJSON,
    DifferentVersionsFromJSONTyped,
    DifferentVersionsToJSON,
    DifferentVersionsToJSONTyped,
} from './DifferentVersions';
import type { RecalculateResponseDisplayDTOs } from './RecalculateResponseDisplayDTOs';
import {
    RecalculateResponseDisplayDTOsFromJSON,
    RecalculateResponseDisplayDTOsFromJSONTyped,
    RecalculateResponseDisplayDTOsToJSON,
    RecalculateResponseDisplayDTOsToJSONTyped,
} from './RecalculateResponseDisplayDTOs';

/**
 * 
 * @export
 * @interface RecalculateResponse
 */
export interface RecalculateResponse {
    /**
     * 
     * @type {RecalculateResponseDisplayDTOs}
     * @memberof RecalculateResponse
     */
    displayDTOs?: RecalculateResponseDisplayDTOs;
    /**
     * 
     * @type {SyncInfo}
     * @memberof RecalculateResponse
     */
    syncInfo?: SyncInfo;
    /**
     * 
     * @type {DifferentVersions}
     * @memberof RecalculateResponse
     */
    differentVersions?: DifferentVersions;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof RecalculateResponse
     */
    itemShiftInfoMap?: { [key: string]: any; };
}

/**
 * Check if a given object implements the RecalculateResponse interface.
 */
export function instanceOfRecalculateResponse(value: object): value is RecalculateResponse {
    return true;
}

export function RecalculateResponseFromJSON(json: any): RecalculateResponse {
    return RecalculateResponseFromJSONTyped(json, false);
}

export function RecalculateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecalculateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'displayDTOs': json['displayDTOs'] == null ? undefined : RecalculateResponseDisplayDTOsFromJSON(json['displayDTOs']),
        'syncInfo': json['syncInfo'] == null ? undefined : SyncInfoFromJSON(json['syncInfo']),
        'differentVersions': json['differentVersions'] == null ? undefined : DifferentVersionsFromJSON(json['differentVersions']),
        'itemShiftInfoMap': json['itemShiftInfoMap'] == null ? undefined : json['itemShiftInfoMap'],
    };
}

export function RecalculateResponseToJSON(json: any): RecalculateResponse {
    return RecalculateResponseToJSONTyped(json, false);
}

export function RecalculateResponseToJSONTyped(value?: RecalculateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'displayDTOs': RecalculateResponseDisplayDTOsToJSON(value['displayDTOs']),
        'syncInfo': SyncInfoToJSON(value['syncInfo']),
        'differentVersions': DifferentVersionsToJSON(value['differentVersions']),
        'itemShiftInfoMap': value['itemShiftInfoMap'],
    };
}

