/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleResponseData } from './ScheduleResponseData';
import {
    ScheduleResponseDataFromJSON,
    ScheduleResponseDataFromJSONTyped,
    ScheduleResponseDataToJSON,
    ScheduleResponseDataToJSONTyped,
} from './ScheduleResponseData';
import type { ToDoListResponseData } from './ToDoListResponseData';
import {
    ToDoListResponseDataFromJSON,
    ToDoListResponseDataFromJSONTyped,
    ToDoListResponseDataToJSON,
    ToDoListResponseDataToJSONTyped,
} from './ToDoListResponseData';

/**
 * 
 * @export
 * @interface RecalculateResponseDisplayDTOs
 */
export interface RecalculateResponseDisplayDTOs {
    /**
     * 
     * @type {ScheduleResponseData}
     * @memberof RecalculateResponseDisplayDTOs
     */
    scheduleResponse?: ScheduleResponseData;
    /**
     * 
     * @type {ToDoListResponseData}
     * @memberof RecalculateResponseDisplayDTOs
     */
    toDoListResponse?: ToDoListResponseData;
}

/**
 * Check if a given object implements the RecalculateResponseDisplayDTOs interface.
 */
export function instanceOfRecalculateResponseDisplayDTOs(value: object): value is RecalculateResponseDisplayDTOs {
    return true;
}

export function RecalculateResponseDisplayDTOsFromJSON(json: any): RecalculateResponseDisplayDTOs {
    return RecalculateResponseDisplayDTOsFromJSONTyped(json, false);
}

export function RecalculateResponseDisplayDTOsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecalculateResponseDisplayDTOs {
    if (json == null) {
        return json;
    }
    return {
        
        'scheduleResponse': json['scheduleResponse'] == null ? undefined : ScheduleResponseDataFromJSON(json['scheduleResponse']),
        'toDoListResponse': json['toDoListResponse'] == null ? undefined : ToDoListResponseDataFromJSON(json['toDoListResponse']),
    };
}

export function RecalculateResponseDisplayDTOsToJSON(json: any): RecalculateResponseDisplayDTOs {
    return RecalculateResponseDisplayDTOsToJSONTyped(json, false);
}

export function RecalculateResponseDisplayDTOsToJSONTyped(value?: RecalculateResponseDisplayDTOs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'scheduleResponse': ScheduleResponseDataToJSON(value['scheduleResponse']),
        'toDoListResponse': ToDoListResponseDataToJSON(value['toDoListResponse']),
    };
}

