/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduleItemData
 */
export interface ScheduleItemData {
    /**
     * 
     * @type {number}
     * @memberof ScheduleItemData
     */
    itemID?: number;
    /**
     * 
     * @type {object}
     * @memberof ScheduleItemData
     */
    item?: object | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduleItemData
     */
    instanceID?: number;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleItemData
     */
    startTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleItemData
     */
    endTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof ScheduleItemData
     */
    color?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduleItemData
     */
    thisPartCompleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleItemData
     */
    instanceStartDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleItemData
     */
    instanceEndDateTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ScheduleItemData
     */
    id?: number;
}

/**
 * Check if a given object implements the ScheduleItemData interface.
 */
export function instanceOfScheduleItemData(value: object): value is ScheduleItemData {
    return true;
}

export function ScheduleItemDataFromJSON(json: any): ScheduleItemData {
    return ScheduleItemDataFromJSONTyped(json, false);
}

export function ScheduleItemDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleItemData {
    if (json == null) {
        return json;
    }
    return {
        
        'itemID': json['ItemID'] == null ? undefined : json['ItemID'],
        'item': json['Item'] == null ? undefined : json['Item'],
        'instanceID': json['InstanceID'] == null ? undefined : json['InstanceID'],
        'startTime': json['StartTime'] == null ? undefined : (new Date(json['StartTime'])),
        'endTime': json['EndTime'] == null ? undefined : (new Date(json['EndTime'])),
        'color': json['Color'] == null ? undefined : json['Color'],
        'thisPartCompleted': json['ThisPartCompleted'] == null ? undefined : json['ThisPartCompleted'],
        'instanceStartDateTime': json['InstanceStartDateTime'] == null ? undefined : (new Date(json['InstanceStartDateTime'])),
        'instanceEndDateTime': json['InstanceEndDateTime'] == null ? undefined : (new Date(json['InstanceEndDateTime'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ScheduleItemDataToJSON(json: any): ScheduleItemData {
    return ScheduleItemDataToJSONTyped(json, false);
}

export function ScheduleItemDataToJSONTyped(value?: ScheduleItemData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ItemID': value['itemID'],
        'Item': value['item'],
        'InstanceID': value['instanceID'],
        'StartTime': value['startTime'] == null ? undefined : ((value['startTime']).toISOString()),
        'EndTime': value['endTime'] == null ? undefined : ((value['endTime']).toISOString()),
        'Color': value['color'],
        'ThisPartCompleted': value['thisPartCompleted'],
        'InstanceStartDateTime': value['instanceStartDateTime'] == null ? undefined : ((value['instanceStartDateTime']).toISOString()),
        'InstanceEndDateTime': value['instanceEndDateTime'] == null ? undefined : ((value['instanceEndDateTime']).toISOString()),
        'id': value['id'],
    };
}

