/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchedulingStatusInfo
 */
export interface SchedulingStatusInfo {
    /**
     * 
     * @type {number}
     * @memberof SchedulingStatusInfo
     */
    bufferDays?: number;
    /**
     * 
     * @type {string}
     * @memberof SchedulingStatusInfo
     */
    missedDependencyTitle?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SchedulingStatusInfo
     */
    specialSchedulingCase?: number;
}

/**
 * Check if a given object implements the SchedulingStatusInfo interface.
 */
export function instanceOfSchedulingStatusInfo(value: object): value is SchedulingStatusInfo {
    return true;
}

export function SchedulingStatusInfoFromJSON(json: any): SchedulingStatusInfo {
    return SchedulingStatusInfoFromJSONTyped(json, false);
}

export function SchedulingStatusInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulingStatusInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'bufferDays': json['bufferDays'] == null ? undefined : json['bufferDays'],
        'missedDependencyTitle': json['missedDependencyTitle'] == null ? undefined : json['missedDependencyTitle'],
        'specialSchedulingCase': json['specialSchedulingCase'] == null ? undefined : json['specialSchedulingCase'],
    };
}

export function SchedulingStatusInfoToJSON(json: any): SchedulingStatusInfo {
    return SchedulingStatusInfoToJSONTyped(json, false);
}

export function SchedulingStatusInfoToJSONTyped(value?: SchedulingStatusInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bufferDays': value['bufferDays'],
        'missedDependencyTitle': value['missedDependencyTitle'],
        'specialSchedulingCase': value['specialSchedulingCase'],
    };
}

