/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModifiedScheduleItem } from './ModifiedScheduleItem';
import {
    ModifiedScheduleItemFromJSON,
    ModifiedScheduleItemFromJSONTyped,
    ModifiedScheduleItemToJSON,
    ModifiedScheduleItemToJSONTyped,
} from './ModifiedScheduleItem';

/**
 * 
 * @export
 * @interface ScheduleItemDiff
 */
export interface ScheduleItemDiff {
    /**
     * 
     * @type {Array<number>}
     * @memberof ScheduleItemDiff
     */
    deletedScheduleItemIds?: Array<number>;
    /**
     * 
     * @type {Array<ModifiedScheduleItem>}
     * @memberof ScheduleItemDiff
     */
    newOrModifiedScheduleItems?: Array<ModifiedScheduleItem>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ScheduleItemDiff
     */
    deletedItemIds?: Array<number>;
}

/**
 * Check if a given object implements the ScheduleItemDiff interface.
 */
export function instanceOfScheduleItemDiff(value: object): value is ScheduleItemDiff {
    return true;
}

export function ScheduleItemDiffFromJSON(json: any): ScheduleItemDiff {
    return ScheduleItemDiffFromJSONTyped(json, false);
}

export function ScheduleItemDiffFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleItemDiff {
    if (json == null) {
        return json;
    }
    return {
        
        'deletedScheduleItemIds': json['deletedScheduleItemIds'] == null ? undefined : json['deletedScheduleItemIds'],
        'newOrModifiedScheduleItems': json['newOrModifiedScheduleItems'] == null ? undefined : ((json['newOrModifiedScheduleItems'] as Array<any>).map(ModifiedScheduleItemFromJSON)),
        'deletedItemIds': json['deletedItemIds'] == null ? undefined : json['deletedItemIds'],
    };
}

export function ScheduleItemDiffToJSON(json: any): ScheduleItemDiff {
    return ScheduleItemDiffToJSONTyped(json, false);
}

export function ScheduleItemDiffToJSONTyped(value?: ScheduleItemDiff | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deletedScheduleItemIds': value['deletedScheduleItemIds'],
        'newOrModifiedScheduleItems': value['newOrModifiedScheduleItems'] == null ? undefined : ((value['newOrModifiedScheduleItems'] as Array<any>).map(ModifiedScheduleItemToJSON)),
        'deletedItemIds': value['deletedItemIds'],
    };
}

