/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScheduleItem } from './ScheduleItem';
import {
    ScheduleItemFromJSON,
    ScheduleItemFromJSONTyped,
    ScheduleItemToJSON,
    ScheduleItemToJSONTyped,
} from './ScheduleItem';
import type { AllDayEvent } from './AllDayEvent';
import {
    AllDayEventFromJSON,
    AllDayEventFromJSONTyped,
    AllDayEventToJSON,
    AllDayEventToJSONTyped,
} from './AllDayEvent';

/**
 * 
 * @export
 * @interface ScheduleResponseData
 */
export interface ScheduleResponseData {
    /**
     * 
     * @type {Date}
     * @memberof ScheduleResponseData
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ScheduleResponseData
     */
    horizon?: Date;
    /**
     * 
     * @type {Array<ScheduleItem>}
     * @memberof ScheduleResponseData
     */
    scheduleItems?: Array<ScheduleItem>;
    /**
     * 
     * @type {Array<AllDayEvent>}
     * @memberof ScheduleResponseData
     */
    allDayEvents?: Array<AllDayEvent>;
}

/**
 * Check if a given object implements the ScheduleResponseData interface.
 */
export function instanceOfScheduleResponseData(value: object): value is ScheduleResponseData {
    return true;
}

export function ScheduleResponseDataFromJSON(json: any): ScheduleResponseData {
    return ScheduleResponseDataFromJSONTyped(json, false);
}

export function ScheduleResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'horizon': json['horizon'] == null ? undefined : (new Date(json['horizon'])),
        'scheduleItems': json['scheduleItems'] == null ? undefined : ((json['scheduleItems'] as Array<any>).map(ScheduleItemFromJSON)),
        'allDayEvents': json['allDayEvents'] == null ? undefined : ((json['allDayEvents'] as Array<any>).map(AllDayEventFromJSON)),
    };
}

export function ScheduleResponseDataToJSON(json: any): ScheduleResponseData {
    return ScheduleResponseDataToJSONTyped(json, false);
}

export function ScheduleResponseDataToJSONTyped(value?: ScheduleResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'startDate': value['startDate'] == null ? undefined : ((value['startDate']).toISOString()),
        'horizon': value['horizon'] == null ? undefined : ((value['horizon']).toISOString()),
        'scheduleItems': value['scheduleItems'] == null ? undefined : ((value['scheduleItems'] as Array<any>).map(ScheduleItemToJSON)),
        'allDayEvents': value['allDayEvents'] == null ? undefined : ((value['allDayEvents'] as Array<any>).map(AllDayEventToJSON)),
    };
}

