/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResponseData } from './SearchResponseData';
import {
    SearchResponseDataFromJSON,
    SearchResponseDataFromJSONTyped,
    SearchResponseDataToJSON,
    SearchResponseDataToJSONTyped,
} from './SearchResponseData';

/**
 * 
 * @export
 * @interface SearchResponseWrapper
 */
export interface SearchResponseWrapper {
    /**
     * 
     * @type {SearchResponseData}
     * @memberof SearchResponseWrapper
     */
    searchResponse?: SearchResponseData;
}

/**
 * Check if a given object implements the SearchResponseWrapper interface.
 */
export function instanceOfSearchResponseWrapper(value: object): value is SearchResponseWrapper {
    return true;
}

export function SearchResponseWrapperFromJSON(json: any): SearchResponseWrapper {
    return SearchResponseWrapperFromJSONTyped(json, false);
}

export function SearchResponseWrapperFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponseWrapper {
    if (json == null) {
        return json;
    }
    return {
        
        'searchResponse': json['searchResponse'] == null ? undefined : SearchResponseDataFromJSON(json['searchResponse']),
    };
}

export function SearchResponseWrapperToJSON(json: any): SearchResponseWrapper {
    return SearchResponseWrapperToJSONTyped(json, false);
}

export function SearchResponseWrapperToJSONTyped(value?: SearchResponseWrapper | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchResponse': SearchResponseDataToJSON(value['searchResponse']),
    };
}

