/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemFull } from './ItemFull';
import {
    ItemFullFromJSON,
    ItemFullFromJSONTyped,
    ItemFullToJSON,
    ItemFullToJSONTyped,
} from './ItemFull';

/**
 * 
 * @export
 * @interface SearchResponseData
 */
export interface SearchResponseData {
    /**
     * 
     * @type {Array<ItemFull>}
     * @memberof SearchResponseData
     */
    items?: Array<ItemFull>;
    /**
     * 
     * @type {boolean}
     * @memberof SearchResponseData
     */
    oldCompletedTasksHidden?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SearchResponseData
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SearchResponseData
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof SearchResponseData
     */
    repeatingAutoScheduledTaskIds?: Array<number> | null;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof SearchResponseData
     */
    tasksMissingDeadlines?: { [key: string]: boolean; } | null;
}

/**
 * Check if a given object implements the SearchResponseData interface.
 */
export function instanceOfSearchResponseData(value: object): value is SearchResponseData {
    return true;
}

export function SearchResponseDataFromJSON(json: any): SearchResponseData {
    return SearchResponseDataFromJSONTyped(json, false);
}

export function SearchResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(ItemFullFromJSON)),
        'oldCompletedTasksHidden': json['oldCompletedTasksHidden'] == null ? undefined : json['oldCompletedTasksHidden'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'repeatingAutoScheduledTaskIds': json['repeatingAutoScheduledTaskIds'] == null ? undefined : json['repeatingAutoScheduledTaskIds'],
        'tasksMissingDeadlines': json['tasksMissingDeadlines'] == null ? undefined : json['tasksMissingDeadlines'],
    };
}

export function SearchResponseDataToJSON(json: any): SearchResponseData {
    return SearchResponseDataToJSONTyped(json, false);
}

export function SearchResponseDataToJSONTyped(value?: SearchResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(ItemFullToJSON)),
        'oldCompletedTasksHidden': value['oldCompletedTasksHidden'],
        'hasNextPage': value['hasNextPage'],
        'hasPreviousPage': value['hasPreviousPage'],
        'repeatingAutoScheduledTaskIds': value['repeatingAutoScheduledTaskIds'],
        'tasksMissingDeadlines': value['tasksMissingDeadlines'],
    };
}

