/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncInfo
 */
export interface SyncInfo {
    /**
     * 
     * @type {string}
     * @memberof SyncInfo
     */
    syncState?: string;
    /**
     * 
     * @type {Date}
     * @memberof SyncInfo
     */
    lastSyncedInAppTime?: Date | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SyncInfo
     */
    calendarAccountSyncStates?: { [key: string]: string; };
}

/**
 * Check if a given object implements the SyncInfo interface.
 */
export function instanceOfSyncInfo(value: object): value is SyncInfo {
    return true;
}

export function SyncInfoFromJSON(json: any): SyncInfo {
    return SyncInfoFromJSONTyped(json, false);
}

export function SyncInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'syncState': json['syncState'] == null ? undefined : json['syncState'],
        'lastSyncedInAppTime': json['lastSyncedInAppTime'] == null ? undefined : (new Date(json['lastSyncedInAppTime'])),
        'calendarAccountSyncStates': json['calendarAccountSyncStates'] == null ? undefined : json['calendarAccountSyncStates'],
    };
}

export function SyncInfoToJSON(json: any): SyncInfo {
    return SyncInfoToJSONTyped(json, false);
}

export function SyncInfoToJSONTyped(value?: SyncInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'syncState': value['syncState'],
        'lastSyncedInAppTime': value['lastSyncedInAppTime'] == null ? undefined : ((value['lastSyncedInAppTime'] as any).toISOString()),
        'calendarAccountSyncStates': value['calendarAccountSyncStates'],
    };
}

