/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';

/**
 * 
 * @export
 * @interface TagListResponse
 */
export interface TagListResponse {
    /**
     * 
     * @type {Array<Tag>}
     * @memberof TagListResponse
     */
    tags?: Array<Tag>;
}

/**
 * Check if a given object implements the TagListResponse interface.
 */
export function instanceOfTagListResponse(value: object): value is TagListResponse {
    return true;
}

export function TagListResponseFromJSON(json: any): TagListResponse {
    return TagListResponseFromJSONTyped(json, false);
}

export function TagListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagFromJSON)),
    };
}

export function TagListResponseToJSON(json: any): TagListResponse {
    return TagListResponseToJSONTyped(json, false);
}

export function TagListResponseToJSONTyped(value?: TagListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagToJSON)),
    };
}

