/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeProfile
 */
export interface TimeProfile {
    /**
     * 
     * @type {number}
     * @memberof TimeProfile
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeProfile
     */
    title?: string;
}

/**
 * Check if a given object implements the TimeProfile interface.
 */
export function instanceOfTimeProfile(value: object): value is TimeProfile {
    return true;
}

export function TimeProfileFromJSON(json: any): TimeProfile {
    return TimeProfileFromJSONTyped(json, false);
}

export function TimeProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['Title'] == null ? undefined : json['Title'],
    };
}

export function TimeProfileToJSON(json: any): TimeProfile {
    return TimeProfileToJSONTyped(json, false);
}

export function TimeProfileToJSONTyped(value?: TimeProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'Title': value['title'],
    };
}

