/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskItem } from './TaskItem';
import {
    TaskItemFromJSON,
    TaskItemFromJSONTyped,
    TaskItemToJSON,
    TaskItemToJSONTyped,
} from './TaskItem';

/**
 * 
 * @export
 * @interface ToDoListResponseData
 */
export interface ToDoListResponseData {
    /**
     * 
     * @type {Array<TaskItem>}
     * @memberof ToDoListResponseData
     */
    tasks?: Array<TaskItem>;
    /**
     * 
     * @type {boolean}
     * @memberof ToDoListResponseData
     */
    oldCompletedTasksHidden?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ToDoListResponseData
     */
    hasNextPage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ToDoListResponseData
     */
    hasPreviousPage?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof ToDoListResponseData
     */
    repeatingAutoScheduledTaskIds?: Array<number> | null;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof ToDoListResponseData
     */
    tasksMissingDeadlines?: { [key: string]: boolean; };
}

/**
 * Check if a given object implements the ToDoListResponseData interface.
 */
export function instanceOfToDoListResponseData(value: object): value is ToDoListResponseData {
    return true;
}

export function ToDoListResponseDataFromJSON(json: any): ToDoListResponseData {
    return ToDoListResponseDataFromJSONTyped(json, false);
}

export function ToDoListResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToDoListResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': json['tasks'] == null ? undefined : ((json['tasks'] as Array<any>).map(TaskItemFromJSON)),
        'oldCompletedTasksHidden': json['oldCompletedTasksHidden'] == null ? undefined : json['oldCompletedTasksHidden'],
        'hasNextPage': json['hasNextPage'] == null ? undefined : json['hasNextPage'],
        'hasPreviousPage': json['hasPreviousPage'] == null ? undefined : json['hasPreviousPage'],
        'repeatingAutoScheduledTaskIds': json['repeatingAutoScheduledTaskIds'] == null ? undefined : json['repeatingAutoScheduledTaskIds'],
        'tasksMissingDeadlines': json['tasksMissingDeadlines'] == null ? undefined : json['tasksMissingDeadlines'],
    };
}

export function ToDoListResponseDataToJSON(json: any): ToDoListResponseData {
    return ToDoListResponseDataToJSONTyped(json, false);
}

export function ToDoListResponseDataToJSONTyped(value?: ToDoListResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tasks': value['tasks'] == null ? undefined : ((value['tasks'] as Array<any>).map(TaskItemToJSON)),
        'oldCompletedTasksHidden': value['oldCompletedTasksHidden'],
        'hasNextPage': value['hasNextPage'],
        'hasPreviousPage': value['hasPreviousPage'],
        'repeatingAutoScheduledTaskIds': value['repeatingAutoScheduledTaskIds'],
        'tasksMissingDeadlines': value['tasksMissingDeadlines'],
    };
}

