/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserActionHistory
 */
export interface UserActionHistory {
    /**
     * 
     * @type {boolean}
     * @memberof UserActionHistory
     */
    hasDismissedReorderHint?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserActionHistory
     */
    hasDismissedCopySchedulingHoursTip?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserActionHistory
     */
    hasDismissedAestheticHardUpdate?: boolean;
}

/**
 * Check if a given object implements the UserActionHistory interface.
 */
export function instanceOfUserActionHistory(value: object): value is UserActionHistory {
    return true;
}

export function UserActionHistoryFromJSON(json: any): UserActionHistory {
    return UserActionHistoryFromJSONTyped(json, false);
}

export function UserActionHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserActionHistory {
    if (json == null) {
        return json;
    }
    return {
        
        'hasDismissedReorderHint': json['HasDismissedReorderHint'] == null ? undefined : json['HasDismissedReorderHint'],
        'hasDismissedCopySchedulingHoursTip': json['HasDismissedCopySchedulingHoursTip'] == null ? undefined : json['HasDismissedCopySchedulingHoursTip'],
        'hasDismissedAestheticHardUpdate': json['HasDismissedAestheticHardUpdate'] == null ? undefined : json['HasDismissedAestheticHardUpdate'],
    };
}

export function UserActionHistoryToJSON(json: any): UserActionHistory {
    return UserActionHistoryToJSONTyped(json, false);
}

export function UserActionHistoryToJSONTyped(value?: UserActionHistory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'HasDismissedReorderHint': value['hasDismissedReorderHint'],
        'HasDismissedCopySchedulingHoursTip': value['hasDismissedCopySchedulingHoursTip'],
        'HasDismissedAestheticHardUpdate': value['hasDismissedAestheticHardUpdate'],
    };
}

