/* tslint:disable */
/* eslint-disable */
/**
 * FlowSavvy API
 * API for managing tasks, events, and schedules on FlowSavvy.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserActionHistory } from './UserActionHistory';
import {
    UserActionHistoryFromJSON,
    UserActionHistoryFromJSONTyped,
    UserActionHistoryToJSON,
    UserActionHistoryToJSONTyped,
} from './UserActionHistory';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    identityUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userHash?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isEmailConfirmed?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    dateCreatedUtc?: Date;
    /**
     * 
     * @type {UserActionHistory}
     * @memberof User
     */
    actionHistory?: UserActionHistory;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'identityUserId': json['identityUserId'] == null ? undefined : json['identityUserId'],
        'email': json['email'] == null ? undefined : json['email'],
        'userHash': json['userHash'] == null ? undefined : json['userHash'],
        'isEmailConfirmed': json['isEmailConfirmed'] == null ? undefined : json['isEmailConfirmed'],
        'dateCreatedUtc': json['dateCreatedUtc'] == null ? undefined : (new Date(json['dateCreatedUtc'])),
        'actionHistory': json['actionHistory'] == null ? undefined : UserActionHistoryFromJSON(json['actionHistory']),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'identityUserId': value['identityUserId'],
        'email': value['email'],
        'userHash': value['userHash'],
        'isEmailConfirmed': value['isEmailConfirmed'],
        'dateCreatedUtc': value['dateCreatedUtc'] == null ? undefined : ((value['dateCreatedUtc']).toISOString()),
        'actionHistory': UserActionHistoryToJSON(value['actionHistory']),
    };
}

